import type { ComponentType } from 'react';
import { IconProps, WaveIcon, ThoughtIcon, StarIcon } from '../../components/icons';
import { ActSkillId } from './actSkillOptions';

export type EventType = 'meltdown' | 'parentReaction' | 'positiveMoment';

export interface ReflectionMessage {
  id: string;
  role: 'assistant' | 'user';
  text: string;
  createdAtISO: string;
  /** Therapist Mode only: the evidence-based approach behind this reply. */
  framework?: string | null;
  /** Whether the professional-disclaimer line should render under this message (already throttled). */
  showsDisclaimer?: boolean;
}

export interface SavedReflection {
  messages: ReflectionMessage[];
  savedAtISO: string;
}

// Structurally matches ai/parentReplay.ts's ParentReplayResult (+
// generatedAtISO) without importing it — that file imports LoggedEvent
// from here, so importing back would be circular. Cached onto the event
// the same way SavedReflection is, so a Parent Replay survives leaving the
// screen instead of only existing in that screen's component state.
export interface SavedParentReplay {
  turns: { speaker: 'child' | 'caregiver'; text: string }[];
  keyMoments: { turnIndex: number; alternative: string; reasoning: string; framework: string | null }[];
  includeDisclaimer: boolean;
  generatedAtISO: string;
}

export interface LoggedEvent {
  id: string;
  eventType: EventType;
  /** ISO string for the date/time the event actually happened (editable by the caregiver). */
  occurredAtISO: string;
  /** Fallback for when the exact time isn't remembered, e.g. "during breakfast". */
  timeDescription: string;
  /** 1-10. Meaningless for positiveMoment (that flow never asks for it) — a placeholder default, never shown in the UI for that type. */
  intensity: number;
  /** Challenge flow (meltdown/parentReaction) only — positiveMoment never asks for this. */
  durationLabel: string;
  /** Challenge flow (meltdown/parentReaction) only — see questionConfig.ts CHALLENGE_QUESTION_STEPS. Empty string for positiveMoment entries. */
  whatHappened: string;
  before: string;
  after: string;
  location: string;
  whoPresent: string;
  consequences: string;
  additionalNotes: string;
  // Positive Moment only — see questionConfig.ts POSITIVE_QUESTION_STEPS.
  // Kept as separate fields (rather than reusing the challenge-flow fields
  // above) so nothing that reads "whatHappened"/"consequences" elsewhere in
  // the app ever has to guess which flow produced an entry.
  /** What made this moment meaningful. */
  meaningfulMoment?: string;
  /** What the child did well. */
  childStrength?: string;
  /** What the caregiver did that helped create the moment. */
  caregiverContribution?: string;
  /** How the moment made the caregiver feel. */
  feelingReflection?: string;
  /** What they'd like to remember about today. */
  memorableDetail?: string;
  /** How to create more moments like this. */
  repeatStrategy?: string;
  /** ISO string for when the entry was saved. */
  createdAtISO: string;
  /** Optional deeper category within eventType, e.g. "reactive" for a meltdown. See subtypeOptions.ts. */
  subtype?: string;
  /** Generated by AI the first time the reflection screen opens for this entry (see ai/aiReflectionEngine.ts). */
  reflection?: SavedReflection;
  /** Generated by AI the first time the Parent Replay screen opens for this entry (see ai/parentReplay.ts). */
  parentReplay?: SavedParentReplay;

  // Four standardized daily check-in questions, asked on every entry
  // regardless of eventType (in addition to the fields above, which stay
  // specific to whichever event type was logged) — see dailyLogQuestions.ts.
  // These are the fields future longitudinal/intervention-progress analysis
  // should read: consistent across every entry, unlike the event-specific
  // fields above which vary by type. Optional because entries logged before
  // this was added won't have them.
  /** Single-Item Daily Parenting Stress Measure: 1 (not stressful) to 7 (extremely stressful). The single most important stat for tracking how the intervention is working over time. */
  dailyStressScore?: number;
  /** "Anything come up today..." — a whole-day note, distinct in scope from the event-specific fields above (which describe one specific incident/moment, not the day as a whole). */
  dailyNote?: string;
  /** Which ACT skill(s) the caregiver used today, if any — see actSkillOptions.ts. */
  actSkillsUsed?: ActSkillId[];
  /** A moment today the caregiver responded in a way that matched what matters to them, even if it was hard. */
  valuesAlignedMoment?: string;
}

export interface EventTypeOption {
  type: EventType;
  label: string;
  icon: ComponentType<IconProps>;
}

export const EVENT_TYPE_OPTIONS: EventTypeOption[] = [
  { type: 'meltdown', label: 'Child Meltdown', icon: WaveIcon },
  { type: 'parentReaction', label: 'Parent Emotional Reaction', icon: ThoughtIcon },
  { type: 'positiveMoment', label: 'Positive Moment', icon: StarIcon },
];
