import type { ComponentType } from 'react';
import { IconProps, WaveIcon, ThoughtIcon, StarIcon } from '../../components/icons';

export type EventType = 'meltdown' | 'parentReaction' | 'positiveMoment';

export interface ReflectionMessage {
  id: string;
  role: 'assistant' | 'user';
  text: string;
  createdAtISO: string;
  /** Therapist Mode only: the evidence-based approach behind this reply. */
  framework?: string | null;
  /** Whether the professional-disclaimer line should render under this message (already throttled). */
  showsDisclaimer?: boolean;
}

export interface SavedReflection {
  messages: ReflectionMessage[];
  savedAtISO: string;
}

export interface LoggedEvent {
  id: string;
  eventType: EventType;
  /** ISO string for the date/time the event actually happened (editable by the caregiver). */
  occurredAtISO: string;
  /** Fallback for when the exact time isn't remembered, e.g. "during breakfast". */
  timeDescription: string;
  /** 1-10. Meaningless for positiveMoment (that flow never asks for it) — a placeholder default, never shown in the UI for that type. */
  intensity: number;
  /** Challenge flow (meltdown/parentReaction) only — positiveMoment never asks for this. */
  durationLabel: string;
  /** Challenge flow (meltdown/parentReaction) only — see questionConfig.ts CHALLENGE_QUESTION_STEPS. Empty string for positiveMoment entries. */
  whatHappened: string;
  before: string;
  after: string;
  location: string;
  whoPresent: string;
  consequences: string;
  additionalNotes: string;
  // Positive Moment only — see questionConfig.ts POSITIVE_QUESTION_STEPS.
  // Kept as separate fields (rather than reusing the challenge-flow fields
  // above) so nothing that reads "whatHappened"/"consequences" elsewhere in
  // the app ever has to guess which flow produced an entry.
  /** What made this moment meaningful. */
  meaningfulMoment?: string;
  /** What the child did well. */
  childStrength?: string;
  /** What the caregiver did that helped create the moment. */
  caregiverContribution?: string;
  /** How the moment made the caregiver feel. */
  feelingReflection?: string;
  /** What they'd like to remember about today. */
  memorableDetail?: string;
  /** How to create more moments like this. */
  repeatStrategy?: string;
  /** ISO string for when the entry was saved. */
  createdAtISO: string;
  /** Optional deeper category within eventType, e.g. "reactive" for a meltdown. See subtypeOptions.ts. */
  subtype?: string;
  /** Generated by AI the first time the reflection screen opens for this entry (see ai/aiReflectionEngine.ts). */
  reflection?: SavedReflection;
}

export interface EventTypeOption {
  type: EventType;
  label: string;
  icon: ComponentType<IconProps>;
}

export const EVENT_TYPE_OPTIONS: EventTypeOption[] = [
  { type: 'meltdown', label: 'Child Meltdown', icon: WaveIcon },
  { type: 'parentReaction', label: 'Parent Emotional Reaction', icon: ThoughtIcon },
  { type: 'positiveMoment', label: 'Positive Moment', icon: StarIcon },
];
